### ISSUE TITLE
Lisp errors on very recent versions of emacs 27 from git

### ISSUE THREAD

**Issue by etu** [dracula/emacs#51]
Hi,

I'm running Emacs 27 from git with this theme. And on recent versions it seem to have broke. The emacs I'm currently testing with seems to be based on this commit: https://github.com/emacs-mirror/emacs/commit/a7d47e64aaf438feaa8cbe4d40acb7bae0eab059

If I'm trying an older one, which I believe is this commit: https://github.com/emacs-mirror/emacs/commit/51cf9161ceaa613a95f714e56fb793dcf62d1da6 it does work.

When I execute the following piece of elisp:
```elisp
(load-theme 'dracula-theme t)
```

I get the following error:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-directory-p(nil)
  custom-theme--load-path()
  load-theme(dracula-theme t)
  (progn (load-theme 'dracula-theme t))
  eval((progn (load-theme 'dracula-theme t)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

I'm not sure what would break in a theme tbh. And from what I can see there's no weirdness in the theme elisp code itself... But yeah. I haven't dug in properly.

**Comment by milouse** [comment]
Hi @etu. Do you still suffer from this bug? Does a more recent version of emacs 27 solves the thing?

Are you sure the theme is accessible from your emacs config file? The crash comes from a wrong `file-directory-p` call. But there is no call to this method in the dracula theme. I think the problem comes from emacs trying to find the file to load, but not finding it.

@tsdh you may have tip regarding this situation as you are already on emacs 27 too…

**Comment by milouse** [comment]
I just take time to compile emacs 27 and try to reproduce this error. I don't: everything load fine at first attempt. Thus I close this ticket.

**Comment by etu** [comment]
@milouse I haven't used emacs27 in a while partly due to this. But I just built it and it starts fine. So it was probably a bug at that time.
