### ISSUE TITLE
How to change the background of selection hightlighting?

### ISSUE THREAD

**Issue by davidshen84** [dracula/emacs#77]
In the screenshot, I started selecting from the last *c* at the top, but there's no visual indication because the colour of that section is also bright yellow.

![image](https://user-images.githubusercontent.com/65741/105654115-7069d980-5f11-11eb-8112-ab08d5e65fd1.png)

Currently, the theme only changes the font colour of the selection and it can conflict with cod highlighting in some cases.

Is there's a way to change the background colour of the selected region?

**Comment by milouse** [comment]
Hi,

Sorry for the long silence, it seems I never receive these notifications :/ Or I remove them by errors in my mailbox.

Your problem is weird because the selection should have a yellow background and a dark font color (the inverse of what you have). So maybe you are using a custom mode badly supported at this time. Can you precise what kind of document your are editing and the mode you are using?

Thank you very much

**Comment by davidshen84** [comment]
I think it is a theme clash issue. I have multiple theme packages installed with `use-package`. I think some other themes override some default value that `dracula` assumed to use the default value.

After disable other themes, this theme works nicely. Thanks!

**Comment by milouse** [comment]
Thank you for your reply!
